---
output:
  pdf_document
header-includes: \usepackage[french]{babel}
---

\newpage
\begin{flushright}
    \textbf{Équipe 8}
\end{flushright}

\begin{center}
    \vspace{2\baselineskip}
    Charles Comeau \\
    (111 185 421) \\
    \vspace{1\baselineskip}
    Nicholas Langevin \\
    (111 184 631) \\
    \vspace{1\baselineskip}
    Andréanne Larouche \\
    (111 190 518) \\
    \vspace{7\baselineskip}
    Apprentissage statistique en actuariat\\
    ACT-3114 \\
    \vspace{7\baselineskip}
    {\large
    \textbf{Analyse des données de renouvellement d'assurance}} \\
    \vspace{8\baselineskip}
    présenté à \\
    Marie-Pier Côté \\
    \vspace{9\baselineskip}
    École d’actuariat \\
    Université Laval \\
    27 février 2020
\end{center}

\newpage

\tableofcontents

```{R , echo = FALSE, include = FALSE, warning = FALSE}
library(CASdatasets)
library(ggplot2)
data(eudirectlapse)
data.init <- eudirectlapse

## Changement dans les donnees
data <- data.init
str(data)
data$lapse <- as.factor(data$lapse)
levels(data$lapse) <- c("renew", "cancelation")
data[data$polholder_diffdriver == "unknown", ]$polholder_diffdriver <- NA
data[data$vehicl_garage == "unknown", ]$vehicl_garage <- NA
data$prem_freqperyear <- factor(data$prem_freqperyear, order = TRUE, levels = c("1 per year", "2 per year", "4 per year", "12 per year"))

data$vehicl_powerkw_na <- data$vehicl_powerkw
data[data$vehicl_powerkw_na == "125-300 kW", ]$vehicl_powerkw_na <- NA
data[data$vehicl_powerkw %in% c("150 kW","175 kW","200 kW","225 kW","250 kW","275 kW","300 kW"), ]$vehicl_powerkw <- "125-300 kW"
data <- droplevels(data)
data$vehicl_powerkw <- factor(data$vehicl_powerkw, order = TRUE, levels = c("25-50 kW", "75 kW", "100 kW", "125-300 kW"))
table(data$vehicl_powerkw)
str(data)

## Diagramme à bande des frequence de renouvellement et decheance en fonction des variables categorielles 
ggplot(data, aes(x=lapse, fill=polholder_BMCevol))+
  geom_bar(position="dodge")
ggplot(data, aes(x=lapse, fill=polholder_diffdriver))+
  geom_bar(position="dodge")
ggplot(data, aes(x=lapse, fill=polholder_gender))+
  geom_bar(position="dodge")
ggplot(data, aes(x=lapse, fill=policy_caruse))+
  geom_bar(position="dodge")
ggplot(data, aes(x=lapse, fill=prem_freqperyear))+
  geom_bar(position="dodge")
ggplot(data, aes(x=lapse, fill=vehicl_garage))+
  geom_bar(position="dodge")
ggplot(data, aes(x=lapse, fill=vehicl_powerkw))+
  geom_bar(position="dodge")
ggplot(data, aes(x=lapse, fill=vehicl_region))+
  geom_bar(position="dodge")

```

\newpage

# Introduction

Les données qui seront analysées dans ce rapport proviennent du jeu de données "eudirectlapse" du paquetage "CASdatasets" de R. Dans le but de modéliser le statut de renouvellement d'une police d'assurance, il sera d'abord nécessaire de visualiser et de pré-traiter les données observées des 23 060 polices d'assurance. Il est à noter que la durée d'observation est de un an et que l'année visée et la compagnie demeurent inconnue. Ainsi, "lapse", variable de type catégorielle qui indique si l'assuré résignera lors de son renouvellement d'assurance ou non, est la variable réponse qui sera intéressante.

\newpage

# Analyse exploratoire des données


\newpage

# Autres sections


\newpage

# Analyse en composantes principales
```{R , echo = FALSE, include = FALSE}
require(tidyverse)
require(FactoMineR)
require(factoextra)
require(plotly)
require(ggplot2)
library(cluster)
```

Étant donné que notre jeu de données contient `R nrow(Donnees_tempo)` observations, il peut être utile de visualiser les données à l'aide de l'analyse en composantes principales, appelé ACP. En effet, ce type d'analyse permet de mieux visualiser un jeu de données lorsque celui-ci est de grande dimension. Il sera ainsi possible de voir quelles variables explicatives sont plus intéressantes par leur impact sur la variance des composantes principales. Il est à noter qu'en général, on garde assez de composantes pour représenter entre 80 et 90 % de la variance totale. 

Pour que cette méthode de visualisation puisse être utilisée, il sera nécessaire de prendre seulement les variables explicatives numériques de ce jeu de donnée. Les variables catégorielles ne seront pas analysées dans cette section car même en les transformant en variables numériques, elles ne seront pas représentative de leur signification.

```{R , echo = FALSE, include = TRUE}
Donnees_tempo <- na.omit(data)
Data_num <- Donnees_tempo[, c("polholder_age", "policy_age", "policy_nbcontract", "prem_final", "prem_last", "prem_market", 
                              "prem_pure", "vehicl_age", "vehicl_agepurchase")]
```

On doit ensuite choisir le nombre de composantes principales. Cette étape peut être complétée en spécifiant le pourcentage de variance expliquée pour obtenir la cible précisée précedemment ou utiliser la méthode du coude sur le diagramme d'éboulis. 

```{R , echo = FALSE, include = FALSE}
ACP <- PCA(Data_num, scale = TRUE, ncp = 6)
```
À l'aide du graphique ACP des variables on peut observer que pour la première composante principlae, une valeur élevé indique un contrat ayant une prime élevé, que ce soit la prime du marché, la prime pure, la prime finale ou la prime chargée lors du dernier renouvellement. Par contre, un assuré âgé aura un score moindre qu'un assuré en bas âge. Un score élevé représente donc un assuré en bas âge ayant une prime élevé tandis qu'un score faible représente une personne plus âgée avec une faible prime d'assurance. 

La deuxième composante principale représente, quant à elle, l'âge du véhicule assuré. Un score élevé est associé à des véhicules de moindres valeurs mais risquant d'avantage un bris de veillesse. Plus les polices d'assurance sont récentes et plus le score en sera augmenté. Ainsi, les polices d'assurances récente ayant des véhicules de l'année représenteront les scores les plus faibles pour cette composante.

```{R , echo = FALSE, include = TRUE}
fviz_screeplot(ACP)
ACP$eig
```

Selon le diagramme d'éboulis, il sera nécessaire de conserver 6 composantes principales et on observe, à l'aide des valeurs propres de la matrice de corélation, que 6 composantes principales permettent d'expliquer 97% de la variance totale.

À l'aide de la fonction ACP, nous pouvons voir la gravité des contributions pour chacune des variables sur chacune des composantes principales retenu. Ainsi, on remarque que la variable *prem_final* est celle ayant la plus grande contribution sur la première composantes principale, tout comme les variable *prem_last*, *prem_market* et *prem_pure*. Quand à la deuxième et à la sixième composante principale, c'est les variables *vehicl_age* et *vehicl_agepurchase* qui fournissent la plus grande contribution. Les variables explicatives *polholder_age* et *policy_age* ont les contributions les plus importantes pour les troisième et cinquième composantes principales. Pour ce qui est de la variable *policy_nbcontract*, elle est la variable apportant la plus grande contribution sur la quatrième composante principale. 

```{R , echo = FALSE, include = TRUE}
ACP$var$contrib
```

En illustrant les contributions des variables pour chacune des composantes principales, il est plus facile de visualiser l'intensité de leur contribution.

```{R , message=FALSE, include = TRUE, echo = FALSE}
contrib <- data.frame(ACP$var$coord[,1:6])
contrib$carac <- rownames(contrib)
contrib.long <- reshape2::melt(contrib)

ggplot(contrib.long, aes(x=carac, fill=variable, y=value))+
  geom_bar(stat="identity",position=PositionDodge)+
  facet_grid(~variable)+
  theme(legend.position="top",axis.text.x = element_text(angle = 90))+
  coord_flip()
```


Diagramme de points (modèle) : À COMPLÉTER ET VÉRIFIER S'IL NE FAUT PAS INCLURE LES VARIABLES CATEGORIELLE ORDINALE TRANSFORMÉES EN VARIABLE NUMÉRQUES
```{R , echo = FALSE, include = TRUE}
data <- cbind(Donnees_tempo, ACP$ind$coord)

g_ind <- ggplot(data = data,
             aes(x= Dim.2, y=Dim.3, col = policy_age,  shape = lapse, labels = polholder_age,
                 alpha = 0.2)) +
  geom_point() +
  xlab("Dimension 2") +
  ylab("Dimension 3") +
  theme_bw()
ggplotly(g_ind) #Pour comparer les dimensions 2 et 3

g_ind <- ggplot(data = data,
             aes(x= Dim.1, y=Dim.2, col = prem_pure,  shape = lapse, labels = vehicl_agepurchase,
                 alpha = 0.2)) +
  geom_point() +
  xlab("Dimension 1") +
  ylab("Dimension 2") +
  theme_bw()
ggplotly(g_ind) #Pour comparer les dimensions 2 et 3
```

\newpage

# Partitionnement en k moyennes

Le partitionnement en k moyennes est utiliser pour classifier les observations en k groupes distincts. La valeur de k est une valeur qu'on transmet pour indiquer le nombre de partitions désirées. Chaque observation sera ensuite assigné à un seul groupe. L'algorithme utilisée pour ce type de partitionnement a pour objectif de minimiser la variance intra-groupe.

```{R , echo = FALSE, include = TRUE}
Data_num <- Donnees_tempo[, c("polholder_age", "policy_age", "policy_nbcontract", "prem_final", "prem_last", "prem_market", 
                              "prem_pure", "vehicl_age", "vehicl_agepurchase")]

K <- 3
kmoyennes <- kmeans(Data_num, K, nstart=5)
Donnees_acp <- PCA(Data_num, scale = FALSE, ncp = 2, graph = FALSE)

composante1 <- Donnees_acp$ind$coord[,1]
composante2 <- Donnees_acp$ind$coord[,2]

groupe <- as.factor(kmoyennes$cluster)

ggplot() + geom_point(aes(composante1, composante2, color = groupe)) + theme_minimal()
```

\newpage

# Conclusion


\newpage

# Annexe

Notre jeu de données représente le statut de renouvellement pour 23 060 polices d'assurance basées sur un an d'observation. Les données receuillies proviennent d'une compagnie d'assurance inconnue dont l'année d'observation est également inconnue.
